#!/usr/bin/python3

from model.carta import Carta
from model.tipocarta import TipoCarta
import pathlib

__path = pathlib.Path(__file__).parent.parent / "imagenes"

cartas = {
    Carta(1, TipoCarta.Corazones): (__path / "corazones" / "1.png").absolute(),
    Carta(2, TipoCarta.Corazones): (__path / "corazones" / "2.png").absolute(),
    Carta(3, TipoCarta.Corazones): (__path / "corazones" / "3.png").absolute(),
    Carta(4, TipoCarta.Corazones): (__path / "corazones" / "4.png").absolute(),
    Carta(5, TipoCarta.Corazones): (__path / "corazones" / "5.png").absolute(),
    Carta(6, TipoCarta.Corazones): (__path / "corazones" / "6.png").absolute(),
    Carta(7, TipoCarta.Corazones): (__path / "corazones" / "7.png").absolute(),
    Carta(8, TipoCarta.Corazones): (__path / "corazones" / "8.png").absolute(),
    Carta(9, TipoCarta.Corazones): (__path / "corazones" / "9.png").absolute(),
    Carta(10, TipoCarta.Corazones): (__path / "corazones" / "10.png").absolute(),
    Carta(11, TipoCarta.Corazones): (__path / "corazones" / "11.png").absolute(),
    Carta(12, TipoCarta.Corazones): (__path / "corazones" / "12.png").absolute(),
    Carta(13, TipoCarta.Corazones): (__path / "corazones" / "13.png").absolute(),
    Carta(1, TipoCarta.Diamantes): (__path / "diamantes" / "1.png").absolute(),
    Carta(2, TipoCarta.Diamantes): (__path / "diamantes" / "2.png").absolute(),
    Carta(3, TipoCarta.Diamantes): (__path / "diamantes" / "3.png").absolute(),
    Carta(4, TipoCarta.Diamantes): (__path / "diamantes" / "4.png").absolute(),
    Carta(5, TipoCarta.Diamantes): (__path / "diamantes" / "5.png").absolute(),
    Carta(6, TipoCarta.Diamantes): (__path / "diamantes" / "6.png").absolute(),
    Carta(7, TipoCarta.Diamantes): (__path / "diamantes" / "7.png").absolute(),
    Carta(8, TipoCarta.Diamantes): (__path / "diamantes" / "8.png").absolute(),
    Carta(9, TipoCarta.Diamantes): (__path / "diamantes" / "9.png").absolute(),
    Carta(10, TipoCarta.Diamantes): (__path / "diamantes" / "10.png").absolute(),
    Carta(11, TipoCarta.Diamantes): (__path / "diamantes" / "11.png").absolute(),
    Carta(12, TipoCarta.Diamantes): (__path / "diamantes" / "12.png").absolute(),
    Carta(13, TipoCarta.Diamantes): (__path / "diamantes" / "13.png").absolute(),
    Carta(1, TipoCarta.Picas): (__path / "picas" / "1.png").absolute(),
    Carta(2, TipoCarta.Picas): (__path / "picas" / "2.png").absolute(),
    Carta(3, TipoCarta.Picas): (__path / "picas" / "3.png").absolute(),
    Carta(4, TipoCarta.Picas): (__path / "picas" / "4.png").absolute(),
    Carta(5, TipoCarta.Picas): (__path / "picas" / "5.png").absolute(),
    Carta(6, TipoCarta.Picas): (__path / "picas" / "6.png").absolute(),
    Carta(7, TipoCarta.Picas): (__path / "picas" / "7.png").absolute(),
    Carta(8, TipoCarta.Picas): (__path / "picas" / "8.png").absolute(),
    Carta(9, TipoCarta.Picas): (__path / "picas" / "9.png").absolute(),
    Carta(10, TipoCarta.Picas): (__path / "picas" / "10.png").absolute(),
    Carta(11, TipoCarta.Picas): (__path / "picas" / "11.png").absolute(),
    Carta(12, TipoCarta.Picas): (__path / "picas" / "12.png").absolute(),
    Carta(13, TipoCarta.Picas): (__path / "picas" / "13.png").absolute(),
    Carta(1, TipoCarta.Trebol): (__path / "treboles" / "1.png").absolute(),
    Carta(2, TipoCarta.Trebol): (__path / "treboles" / "2.png").absolute(),
    Carta(3, TipoCarta.Trebol): (__path / "treboles" / "3.png").absolute(),
    Carta(4, TipoCarta.Trebol): (__path / "treboles" / "4.png").absolute(),
    Carta(5, TipoCarta.Trebol): (__path / "treboles" / "5.png").absolute(),
    Carta(6, TipoCarta.Trebol): (__path / "treboles" / "6.png").absolute(),
    Carta(7, TipoCarta.Trebol): (__path / "treboles" / "7.png").absolute(),
    Carta(8, TipoCarta.Trebol): (__path / "treboles" / "8.png").absolute(),
    Carta(9, TipoCarta.Trebol): (__path / "treboles" / "9.png").absolute(),
    Carta(10, TipoCarta.Trebol): (__path / "treboles" / "10.png").absolute(),
    Carta(11, TipoCarta.Trebol): (__path / "treboles" / "11.png").absolute(),
    Carta(12, TipoCarta.Trebol): (__path / "treboles" / "12.png").absolute(),
    Carta(13, TipoCarta.Trebol): (__path / "treboles" / "13.png").absolute(),
}
